#!/usr/bin/python
import dbus
import errno
import fuse
import os
import stat
import time
import sys


bus = dbus.connection.Connection("unix:path=/sys/fs/cgroup/cgmanager/sock")

cgmanager = bus.get_object("org.linuxcontainers.cgmanager",
                           "/org/linuxcontainers/cgmanager")
controllers = [str(entry) for entry in cgmanager.ListControllers()]


def expand_range(intrange):
    """
        Takes a string representing a list of integers and integer
        ranges and returns an expanded list of integers.
    """

    result = []
    for part in intrange.split(','):
        if '-' in part:
            a, b = part.split('-')
            a, b = int(a), int(b)
            result.extend(range(a, b + 1))
        else:
            a = int(part)
            result.append(a)
    return result


def get_cgroup(pid, controller):
    """
        Takes a pid and a cgroup controller name and returns the full
        cgroup path for that task.
    """

    with open("/proc/%s/cgroup" % pid, "r") as fd:
        for line in fd:
            fields = line.split(":")
            if fields[1] == controller:
                return fields[2].strip()


def get_cpuinfo():
    """
        Generates a new /proc/cpuinfo
    """

    uid, gid, pid = fuse.fuse_get_context()

    # Grab the current global values
    with open("/proc/cpuinfo", "r") as fd:
        cpus = fd.read().split("\n\n")

    # Grab the current cgroup values
    value = cgmanager.GetValue("cpuset",
                               get_cgroup(pid, "cpuset"),
                               "cpuset.cpus")

    # Generate the new cpuinfo
    entries = []
    count = 0
    for i in expand_range(value):
        entries.append(cpus[i].replace("processor\t: %s" % i,
                                       "processor\t: %s" % count))
        count += 1

    return "%s\n" % "\n\n".join(entries)


def get_meminfo():
    """
        Generates a new /proc/meminfo
    """

    uid, gid, pid = fuse.fuse_get_context()

    # Grab the current global values
    meminfo = []
    with open("/proc/meminfo", "r") as fd:
        for line in fd:
            fields = line.split(":")

            key = fields[0].strip()

            value_fields = fields[1].strip().split()
            value = int(value_fields[0])
            unit = ""
            if len(value_fields) > 1:
                unit = value_fields[1]

            meminfo.append((key, value, unit))

    # Grab the current cgroup values
    cgroup = get_cgroup(pid, "memory")

    cgm = {}
    cgm['limit_in_bytes'] = int(cgmanager.GetValue("memory", cgroup,
                                                   "memory.limit_in_bytes"))
    cgm['usage_in_bytes'] = int(cgmanager.GetValue("memory", cgroup,
                                                   "memory.usage_in_bytes"))

    cgm_stat = cgmanager.GetValue("memory", cgroup, "memory.stat")
    cgm['stat'] = {}
    for line in cgm_stat.split("\n"):
        fields = line.split()
        cgm['stat'][fields[0].strip()] = fields[1].strip()

    # Update the values
    meminfo_dict = {}
    for i in range(len(meminfo)):
        key, value, unit = meminfo[i]
        if key == "MemTotal":
            if cgm['limit_in_bytes'] < value * 1024:
                value = cgm['limit_in_bytes'] / 1024

        elif key == "MemFree":
            value = meminfo_dict['MemTotal'] - cgm['usage_in_bytes'] / 1024

        elif key == "MemAvailable":
            value = meminfo_dict['MemFree']

        elif key == "Cached":
            value = int(cgm['stat']['total_cache']) / 1024

        elif key in ("Buffers", "SwapCached"):
            value = 0

        meminfo[i] = (key, value, unit)
        meminfo_dict[key] = value

    # Generate the new meminfo file
    output = ""
    for key, value, unit in meminfo:
        if unit:
            output += "{key:15} {value} {unit}\n".format(key="%s:" % key,
                                                         value="%8lu" % value,
                                                         unit=unit)
        else:
            output += "{key:15} {value}\n".format(key="%s:" % key,
                                                  value="%8lu" % value)

    return output


def get_stat():
    """
        Generates a new /proc/stat
    """

    uid, gid, pid = fuse.fuse_get_context()

    value = expand_range(cgmanager.GetValue("cpuset",
                                            get_cgroup(pid, "cpuset"),
                                            "cpuset.cpus"))

    output = ""
    count = 0
    with open("/proc/stat", "r") as fd:
        for line in fd:
            if line.startswith("cpu") and not line.startswith("cpu "):
                for cpu in value:
                    if not line.startswith("cpu%s" % cpu):
                        continue

                    line = line.replace("cpu%s" % cpu, "cpu%s" % count)
                    count += 1
                    break
                else:
                    continue
            output += line

    return output


def get_uptime():
    """
        Generates a new /proc/uptime
    """

    uid, gid, pid = fuse.fuse_get_context()

    value = cgmanager.GetTasks("cpuset",
                               get_cgroup(pid, "cpuset"))

    oldest_pid = sorted([os.stat("/proc/%s" % entry).st_ctime
                         for entry in value])[0]

    with open("/proc/uptime", "r") as fd:
        fields = fd.read().split()
        fields[0] = str(round(time.time() - oldest_pid, 2))

    return "%s\n" % " ".join(fields)


def list_cgroup_entries(controller, path):
    """
        List the directory entries for a given cgroup path.
    """

    cg_path = "/%s" % "/".join(path)

    entries = [{'path': ".",
                'type': stat.S_IFDIR,
                'mode': 0o755,
                'uid': 0,
                'gid': 0},
               {'path': "..",
                'type': stat.S_IFDIR,
                'mode': 0o755,
                'uid': 0,
                'gid': 0}]

    entries += [{'path': str(entry[0]),
                 'type': stat.S_IFREG,
                 'uid': entry[1],
                 'gid': entry[2],
                 'mode': entry[3]}
                for entry in cgmanager.ListKeys(controller, cg_path)]
    entries += [{'path': str(entry),
                 'type': stat.S_IFDIR,
                 'mode': 0o755,
                 'uid': 0,
                 'gid': 0}
                for entry in cgmanager.ListChildren(controller, cg_path)]
    return entries


# List of supported files with their callback function
files = {'/proc/cpuinfo': get_cpuinfo,
         '/proc/meminfo': get_meminfo,
         '/proc/stat': get_stat,
         '/proc/uptime': get_uptime}


class LXCFuse(fuse.LoggingMixIn, fuse.Operations):
    def __init__(self, path='.'):
        self.root = path

    def getattr(self, path, fh=None):
        st = {}
        st['st_atime'] = time.time()
        st['st_ctime'] = time.time()
        st['st_mtime'] = time.time()

        if path == "/":
            st['st_mode'] = stat.S_IFDIR | 0o755
            st['st_nlink'] = 2
        elif path == "/cgroup":
            st['st_mode'] = stat.S_IFDIR | 0o755
            st['st_nlink'] = 2
        elif path.startswith("/cgroup/"):
            parts = path.split("/")
            if len(parts) < 3:
                raise fuse.FuseOSError(errno.ENOENT)
            elif len(parts) == 3 and parts[2] in controllers:
                st['st_mode'] = stat.S_IFDIR | 0o755
                st['st_nlink'] = 2
            else:
                entries = list_cgroup_entries(parts[2], parts[3:-1])
                match = [entry for entry in entries
                         if entry['path'] == os.path.basename(path)]
                if not match:
                    raise fuse.FuseOSError(errno.ENOENT)

                if match[0]['type'] == stat.S_IFDIR:
                    st['st_nlink'] = 2
                else:
                    st['st_nlink'] = 1
                st['st_mode'] = match[0]['type'] | match[0]['mode']
                st['st_uid'] = match[0]['uid']
                st['st_gid'] = match[0]['gid']

                if match[0]['type'] == stat.S_IFREG \
                        and parts[-1] not in ("cgroup.event_control",):
                    cg_path = "/%s" % "/".join(parts[3:-1])
                    st['st_size'] = len(cgmanager.GetValue(parts[2],
                                                           cg_path,
                                                           parts[-1])) + 1
        elif path == "/proc":
            st['st_mode'] = stat.S_IFDIR | 0o755
            st['st_nlink'] = 2
        elif path in files:
            st['st_mode'] = stat.S_IFREG | 0o444
            st['st_nlink'] = 1
            st['st_size'] = len(files[path]())
        else:
            raise fuse.FuseOSError(errno.ENOENT)
        return st

    def readdir(self, path, fh):
        if path == "/":
            return ['.', '..', 'proc', 'cgroup']
        elif path == "/cgroup":
            return [".", ".."] + controllers
        elif path.startswith("/cgroup/"):
            parts = path.split("/")
            if parts[2] not in controllers:
                raise fuse.FuseOSError(errno.ENOENT)
            return [entry['path']
                    for entry in list_cgroup_entries(parts[2], parts[3:])]
        elif path == "/proc":
            return ['.', '..'] + [os.path.basename(entry)
                                  for entry in files.keys()
                                  if entry.startswith("/proc/")]
        else:
            raise fuse.FuseOSError(errno.ENOENT)

    def read(self, path, size, offset, fh):
        if path in files:
            content = files[path]()
        elif path.startswith("/cgroup/"):
            parts = path.split("/")
            entries = list_cgroup_entries(parts[2], parts[3:-1])
            match = [entry for entry in entries
                     if entry['path'] == os.path.basename(path)]
            if not match:
                raise fuse.FuseOSError(errno.ENOENT)

            cg_path = "/%s" % "/".join(parts[3:-1])
            content = str(cgmanager.GetValue(parts[2], cg_path, parts[-1]))
            content += "\n"
        else:
            raise fuse.FuseOSError(errno.ENOENT)

        slen = len(content)
        if offset < slen:
            if offset + size > slen:
                size = slen - offset
            buf = content[offset:offset+size]
        else:
            buf = ''
        return buf


server = fuse.FUSE(LXCFuse(), sys.argv[1], allow_other=True,
                   foreground=True)
